---
abstract: 'Perl extension for embedding Lua scripts into Perl code'
author:
  - 'Tassilo von Parseval <tassilo.von.parseval@rwth-aachen.de>'
  - 'Rob Hoelz <rob@hoelz.ro>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Inline-Lua
no_index:
  directory:
    - t
    - inc
requires:
  Inline: 0
  Test::More: 0
version: 0.05
